services:
  - type: web
    name: survey-app-backend
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: waitress-serve --host=0.0.0.0 --port=$PORT main:app

